### ISSUE TITLE
I can see three sports

### ISSUE THREAD

**Issue by Kevinwey** [Kevinwey/capstone_sport-synergie#2]
### **Value Proposition**
<hr>

**As a** User
**I want to** see three sports
**so that** I have an better overview

### **Description**
<hr>

![Image](https://user-images.githubusercontent.com/123939438/229362090-a4fe49e4-b1f2-42f2-9a49-47d12d6452e7.png)

### **Acceptance Criteria**
<hr>

- [x] three random sports are displayed in a list
- [x] sorted by name

### **Tasks**
<hr>

**Comment by rabe200** [comment]
lgtm
