### ISSUE TITLE
I´m able to find my sport

### ISSUE THREAD

**Issue by Kevinwey** [Kevinwey/capstone_sport-synergie#20]
### **Value Proposition**
<hr>

**As a** User
**I want to** be able to easily find a sport that matches my interests and fitness
**so that** I can start my training journey with confidence and ease

### **Description**
<hr>

![Image](https://user-images.githubusercontent.com/123939438/231118033-71aa6756-4def-4c4a-8882-531e55659a54.png)

### **Acceptance Criteria**
<hr>

- [x] the sports given on the `SelectorPage` matches my form input

### **Tasks**
<hr>

**Comment by malgosiam** [comment]
LGTM!
